### ISSUE TITLE
Exit from repl by Command

### ISSUE THREAD

**Issue by goosedb** [sdiehl/repline#35]
Can we provide a way to exit from repl by Command like `:quit` in GHCi?
I'm ready to implement this

**Comment by adamwespiser** [comment]
There are no reserved words provided Repline, and I don't want users forced into a set reserved words which could potentially conflict with commands they already have.

Instead, if you are looking for a way to do "quit", dhall works around this problem here: https://github.com/dhall-lang/dhall-haskell/blob/master/dhall/src/Dhall/Repl.hs#L507

**Comment by goosedb** [comment]
@adamwespiser  I didn't mean hardcoded command. Just a way to soft exit from REPL. A command can, for example, set a flag, that checked every REPL's step and if it's True, call finalizer. 
I think to throw an exception to escape REPL is not the best solution.
